#ifdef CIRQUE_ENABLE
    #ifdef CIRQUE_PINNACLE_TAPPING_TERM
        #undef CIRQUE_PINNACLE_TAPPING_TERM
        #define CIRQUE_PINNACLE_TAPPING_TERM 9999
    #endif
    #ifdef CIRQUE_PINNACLE_TOUCH_DEBOUNCE
        #undef CIRQUE_PINNACLE_TOUCH_DEBOUNCE
        #define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 9999
    #endif
#endif

#define TAPPING_TERM 175
#define PERMISSIVE_HOLD

#ifdef ENCODER_RESOLUTION
#undef ENCODER_RESOLUTION
#endif
#define ENCODER_RESOLUTION 4
