// Cirque
#ifdef POINTING_DEVICE_ENABLE
#    define CIRQUE_PINNACLE_ADDR 0x2A
#    define POINTING_DEVICE_ROTATION_90 // If using fingerpunch case
#    define POINTING_DEVICE_TASK_THROTTLE_MS 5
#    define I2C1_CLOCK_SPEED 400000
#    define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2
#    ifdef CIRQUE_PINNACLE_TAPPING_TERM
#        undef CIRQUE_PINNACLE_TAPPING_TERM
#        define CIRQUE_PINNACLE_TAPPING_TERM 9999
#    endif
#    ifdef CIRQUE_PINNACLE_TOUCH_DEBOUNCE
#        undef CIRQUE_PINNACLE_TOUCH_DEBOUNCE
#        define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 9999
#    endif
#    define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#    define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#endif

// Encoder
#define ENCODER_MAP_KEY_DELAY 10

// OLED
#ifdef OLED_ENABLE
#    define OLED_DISPLAY_128X64
#endif

// Quantum Painter
#ifdef QUANTUM_PAINTER_ENABLE
#    define QUANTUM_PAINTER_DISPLAY_TIMEOUT 3000
#endif
